### ISSUE TITLE
Erreurs d'affichage

### ISSUE THREAD

**Issue by bibeauv** [gch-poly/gch-python#7]
J'ai fait des tests sur 3 browsers différents (Microsoft Edge, Chrome et Firefox) et tout fonctionne de la même manière, bonne nouvelle :)
En faisant les tests, j'ai remarqué 3 erreurs :
Thème 2 :
- Quand je roule toutes les cellules, la 14e "run", il y a une erreur avec la matrice qui permet de faire l'image floutée de Lanna. Selon ce que j'ai compris vite vite avec une recherche, c'est une erreur de mémoire. Cette erreur arrive seulement avec le notebook de Jupyterlite, ça fonctionne avec VS Code.
Thèmes 2 et 3 :
- Les images n'apparaissent pas. Il faudra changer le "path" des images.
`main/content/theme3`
Thème 3 - Exemple sur la diffusion thermique :
- Erreur sur les 3 dernières images, le imshow est "crop" pour une raison bizarre. Ça fait cette erreur seulement sur Jupyterlite. Sur VS Code par exemple, ça marche.
<img width="405" alt="crop" src="https://user-images.githubusercontent.com/50414572/181587175-1c6f23ef-a4c1-4e3d-b620-d027b9b2ce04.png">

À vérifier lorsque tu déploiras avec ton prochain Pull Request, peut-être que tu as déjà vu tout ça :)

**Comment by samayala22** [comment]
**Les erreurs devraient être réglées.**

Pour avoir la dernière version du fichier il faut le `delete` puis rafraichir la page. 

![image](https://user-images.githubusercontent.com/72941105/181622411-350ff703-93a2-49ee-8d2d-073a50540809.png)

C'est pas très élégant et ya plusieurs issues qui le mentionnent dans le repo de jupyterlite donc c'est probablement quelque chose qui va changer dans le futur. 

Le `Revert to Checkpoint`, que je t'avais montré, ne marche pas.

**Comment by bibeauv** [comment]
Super, les images et Lenna apparaissent :)
As-tu toi aussi le problème avec le graphique de diffusion ?

**Comment by bibeauv** [comment]
Laisse faire, tout fonctionne !
Good job, je vais déployer les Notebook sur Moodle :)
